---
version: '3.2'
services:
  mariadb:
    image: docker.io/mariadb:${MARIADB_CONTAINER_VERSION}
    container_name: horde_db
    # Use volumes to have a persistent DB
    # volumes:
    #   - ./horde-db/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
    ports:
      - "3306:3006"
    networks:
      - hordenet

  horde:
    image: docker.pkg.github.com/maintaina/containers/${HORDE_IMAGE}
    container_name: horde_web
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
      - HORDE_ADMIN_USER=${HORDE_ADMIN_USER}
      - HORDE_ADMIN_PASSWORD=${HORDE_ADMIN_PASSWORD}
    volumes:
      - ./web/horde/config/conf.php:/srv/www/horde/web/horde/config/conf.php
      - ./createUser.php:/srv/www/horde/web/horde/bin/createUser.php
    ports:
      - "80:80"
    networks:
      - hordenet
    command: /usr/sbin/apachectl -D FOREGROUND
    tty: true

networks:
  hordenet:
    driver: bridge
