---
version: '3.3'
services:
  mariadb:
    image: docker.io/mariadb:${MARIADB_CONTAINER_VERSION}
    container_name: ${MYSQL_HOSTNAME}
    hostname: ${MYSQL_HOSTNAME}
    # Use volumes to have a persistent DB
    volumes:
     - ./horde-db/:/var/lib/mysql/
    volumes:
      # fixture for the postfix domain table in the database
      # TODO: supply domains via environment variable
      - ./mariadb/domaintable.sql:/docker-entrypoint-initdb.d/postfix-domaintable.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
## Uncomment to expose database ports
   #ports:
   #  - "3306:3006"
    expose:
      - 3306
    networks:
      - hordenet

  dovecot:
    image: ghcr.io/boekhorstb1/containers/dovecot-horde:latest
    container_name: ${CONTAINER_PREFIX}horde_dovecot
    environment:
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - EXPAND_CONFIGS=${EXPAND_CONFIGS}
    ## Use a config volume to provide a completely different config and certs
    # volumes:
    #   - ./dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
    #   - ./dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
    networks:
      - hordenet
#    entrypoint: ["/sbin/tini", "--", "/usr/local/bin/entrypoint.sh"]
#    command: ["/usr/sbin/dovecot", "-F"]
## Uncomment to expose imap port to all host interfaces
#    ports:
#    - "143:143"

  postfix:
    image: ghcr.io/boekhorstb1/containers/postfix-horde:latest
    container_name: ${CONTAINER_PREFIX}horde_postfix
    environment:
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - EXPAND_CONFIGS=${EXPAND_CONFIGS}
      - HORDE_DOMAIN=${HORDE_DOMAIN}
      - CONTAINER_PREFIX=${CONTAINER_PREFIX}
    # volumes:
    #   - ./postfix/mysql_virtual_mailbox_domains.cf:/etc/postfix/mysql_virtual_mailbox_domains.cf
    #   - ./postfix/mysql_virtual_mailbox_maps.cf:/etc/postfix/mysql_virtual_mailbox_maps.cf
    networks:
      - hordenet
## Uncomment to expose SMTP and SMTP-Submission ports
#    ports:
#    - "25:25"
#    - "587:587"

  horde:
    image: ghcr.io/boekhorstb1/containers/${HORDE_IMAGE}
    container_name: ${CONTAINER_PREFIX}horde_web
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_HORDE_USER}
      - MYSQL_PASSWORD=${MYSQL_HORDE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HORDE_DB}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - HORDE_ADMIN_USER=${HORDE_ADMIN_USER}
      - HORDE_ADMIN_PASSWORD=${HORDE_ADMIN_PASSWORD}
      - EXPAND_CONFIGS=${EXPAND_CONFIGS}
      - HORDE_MIGRATION_RUNS=${HORDE_MIGRATION_RUNS}
      - GITHUB_COMPOSER_TOKEN=${GITHUB_COMPOSER_TOKEN}
      - ENABLE_DEVELOPER_MODE=${ENABLE_DEVELOPER_MODE}
      - CUSTOM_TOOLS=${CUSTOM_TOOLS}
    volumes:
      - ./original_config/apps/:/srv/original_config/apps
      ## Uncomment these two to provide your own letsencrypt certs and vhosts file
      ## - /etc/letsencrypt/:/etc/letsencrypt/
      ## Don't forget to copy the template to a .conf file and edit all relevant values
      ## - ./vhosts.d/:/etc/apache2/vhosts.d/
    expose:
      - 80
    ## Comment if you do not want to expose ports directly and rather use a frontend service
    ports:
      - "8080:80"
    # - "443:443"
    networks:
      - hordenet
    command: /usr/sbin/apachectl -D FOREGROUND
    tty: true

networks:
  hordenet:
    name: ${CONTAINER_PREFIX}hordenet
    driver: bridge
