#!/bin/bash

CMD="command -v wget"
PHPUNITVERSION="phpunit-9.phar"
PHPUNITURL="https://phar.phpunit.de/$PHPUNITVERSION"


if ! docker exec -i insys_master_web bash -c "$CMD" &> /dev/null
then
    echo "wget could not be found, installing it now"
    CMD="zypper -n install wget"
    docker exec -i  insys_master_web bash -c "$CMD"
fi

CMD="cd /usr/local/bin/ && wget -O phpunit $PHPUNITURL && chmod +x phpunit && phpunit --version"
docker exec -i insys_master_web bash -c "$CMD"